{
    "name": "Broadcast",
    "version": "1.0.5",
    "icon": "far fa-comments",
    "category": "entertainment",
    "author": "Lazza",
    "maintainers": [
        "Psycho"
    ],
    "desc": "Broadcast voice message to satellites",
    "aliceMinVersion": "1.0.0-b1",
    "systemRequirements": [],
    "pipRequirements": [],
    "conditions": {
        "lang": [
            "en",
			"de"
        ],
        "asrArbitraryCapture": true
    }
}
